### ISSUE TITLE
Accidental Swastika

### ISSUE THREAD

**Issue by Narnillian** [t3l3machus/hoaxshell#1]
I haven't even used this yet, but the 'X' in the image of the README looks a lot like the famous Nazi symbol. You might want to redesign that letter

**Comment by zeroc00I** [comment]
i do agree

**Comment by SavSanta** [comment]
Ha ha oh boy. just say its the original Buddhist symbol instead if anyone asks.

**Comment by t3l3machus** [comment]
Hey guys, sorry, my bad. I totally forgot to mention. You have to be a Nazi to use this tool.

Kidding. Surprisingly, it's really hard to make a descent, 3 rows high "X" symbol, that also fits with the rest of the letters.
For history's sake and additionally to @SavSanta comment, the symbol used to have a positive meaning in ancient times, appearing in various cultures. Let's not forget, the one in hoaxshell is similar, but not the same.
