### ISSUE TITLE
What if there's two simulteneous connection happen?

### ISSUE THREAD

**Issue by YpvzuBohdygxn9257** [t3l3machus/hoaxshell#13]
Does the second connection gets ignored since there isn't an to choose which connection to interact with.

**Comment by t3l3machus** [comment]
Yes, the second connection gets ignored ¯\_(ツ)_/¯
When i started the project, i thought of adding multiple sessions support (like toxssin has for example) but eventually didn't go for it.

**Comment by YpvzuBohdygxn9257** [comment]
is it cool if you add the feature?

**Comment by t3l3machus** [comment]
It's possible yeah, but it's gonna take some time.

**Comment by YpvzuBohdygxn9257** [comment]
sure. take your time no rush

**Comment by Cvetaca** [comment]
This would be a perfect upgrade. Love your work. Thx

**Comment by t3l3machus** [comment]
I guess [Villain](https://github.com/t3l3machus/Villain) settles this :)
