### ISSUE TITLE
Invoke-WebRequest and Invoke-Expression

### ISSUE THREAD

**Issue by simonm2403** [t3l3machus/hoaxshell#15]
When I try to run the payload from my Linux Kali VMWARE machine on my Win11 pc, I get the Invoke-WebRequest cant establish a connection to remote desktop and Invoke-Expression : Cannot bind argument to parameter 'Command' because it is null. 

Any ideas how to fix this?

**Comment by t3l3machus** [comment]
Hi, this seems like a networking problem. Are you sure the two machines can reach each other?

**Comment by simonm2403** [comment]
I Tried to use the curl command on the victim machine, but cant seem to get a connection even though i'm using bridged as network adapter in VMware

**Comment by t3l3machus** [comment]
You must resolve the networking issue, then it will work just fine. Try different network adapter settings in VMware (maybe NAT?).
