### ISSUE TITLE
Error: Unable to connect to remote server

### ISSUE THREAD

**Issue by Endlord15** [t3l3machus/hoaxshell#21]
Whenever I try to run the command I get an error saying Unable to connect to remote server and Cannot bind argument to parameter 'Command' because it is null

![VirtualBoxVM_rF5q23OybT](https://user-images.githubusercontent.com/73094718/195261149-0d5ced86-59d7-4edb-9bc8-b5a3bc6f44ed.png)

**Comment by t3l3machus** [comment]
Hi, this is probably a networking issue. Are you sure the machines you are testing this against can reach one another? check out this [issue](https://github.com/t3l3machus/hoaxshell/issues/15) as well.

**Comment by Endlord15** [comment]
> Hi, this is probably a networking issue. Are you sure the machines you are testing this against can reach one another? check out this [issue](https://github.com/t3l3machus/hoaxshell/issues/15) as well.

I'm using 2 Virtualbox machines on the same computer they should be able to reach each other.

**Comment by t3l3machus** [comment]
@Endlord15 you should run a test to verify if they are communicating, e.g., run a simple python http server on the attacker machine and try to curl something from the victim.
