### ISSUE TITLE
Invoke-WebRequest error while running any command

### ISSUE THREAD

**Issue by Aayushpatil77** [t3l3machus/hoaxshell#24]
![image](https://user-images.githubusercontent.com/65178660/195341040-928e9195-70ce-43e2-8ff4-16bf3163a662.png)

I am receiving the above error while running any command

**Comment by t3l3machus** [comment]
@Aayushpatil77 use `-i` to resolve this. Explained here --> [issue 8](https://github.com/t3l3machus/hoaxshell/issues/8)
