### ISSUE TITLE
Is this linux only?

### ISSUE THREAD

**Issue by jacklolidk** [t3l3machus/hoaxshell#26]

**Comment by Endlord15** [comment]
No this works on Windows, Mac, and Linux!

**Comment by Endlord15** [comment]
> No this works on Windows, Mac, and Linux!

You'll have to skip some steps and find your IP address a different way but it should be the same!

**Comment by ofsanjay1** [comment]
This is powershell and python based so it works on windows. You just need the ip of your system. Everything work same.

**Comment by jacklolidk** [comment]
oddly
Collecting readline
  Downloading readline-6.2.4.1.tar.gz (2.3 MB)
     ---------------------------------------- 2.3/2.3 MB 29.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error: this module is not meant to work on Windows
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by t3l3machus** [comment]
It can run on Windows but it was neither designed nor properly tested to do so successfully.
