### ISSUE TITLE
Domain does not work

### ISSUE THREAD

**Issue by GalloNero96** [t3l3machus/hoaxshell#29]
It is not possible to use a domain instead of a ip address.

89..."parser.add_argument("-s", "--server-ip", action="store", help = "Your hoaxshell server ip address or **domain**.")"

darkside@darksidepi:~/hoaxshell $ ./hoaxshell.py -s exampledomain.net

    ┬ ┬ ┌─┐ ┌─┐ ─┐ ┬ ┌─┐ ┬ ┬ ┌─┐ ┬   ┬  
    ├─┤ │ │ ├─┤ ┌┴┬┘ └─┐ ├─┤ ├┤  │   │  
    ┴ ┴ └─┘ ┴ ┴ ┴ └─ └─┘ ┴ ┴ └─┘ ┴─┘ ┴─┘
                           by t3l3machus

[Debug] IP address is not valid.

**Comment by t3l3machus** [comment]
to use a domain you also need to:
- use `-t` option. 
- provide cert and key files with `-c` and -`k`
