### ISSUE TITLE
Crashes when changing directory

### ISSUE THREAD

**Issue by pr0b3r7** [t3l3machus/hoaxshell#3]
Hi - good job on the FUD on win defender 
I'm having an issue where I'm not able to cd to any dir 
<img width="2640" alt="image" src="https://user-images.githubusercontent.com/14915771/180606769-3e2b9779-b261-41a3-bb2c-def1fba62a41.png">
The same issue occurs when opening calc.exe - 
<img width="629" alt="image" src="https://user-images.githubusercontent.com/14915771/180606882-20868627-fb33-4be2-adbf-a390a07e33c0.png">
Stack trace shows 
hoaxshell > calc.exe----------------------------------------Exception occurred during processing of request from ('100.77.140.74', 50237)Traceback (most recent call last):  File "/usr/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock    self.process_request(request, client_address)  File "/usr/lib/python3.10/socketserver.py", line 347, in process_request    self.finish_request(request, client_address)  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request    self.RequestHandlerClass(request, client_address, self)  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__    self.handle()  File "/usr/lib/python3.10/http/server.py", line 425, in handle    self.handle_one_request()  File "/usr/lib/python3.10/http/server.py", line 413, in handle_one_request    method()  File "/opt/hoaxshell/hoaxshell.py", line 306, in do_POST    to_b_numbers = [ int(n) for n in bin_output ]  File "/opt/hoaxshell/hoaxshell.py", line 306, in <listcomp>    to_b_numbers = [ int(n) for n in bin_output ]ValueError: invalid literal for int() with base 10: ''
doesn't seem to me it is the syntax either - 
<img width="629" alt="image" src="https://user-images.githubusercontent.com/14915771/180607037-8f8efa9c-33fe-4036-a318-a418a995738a.png">

**Comment by pr0b3r7** [comment]
This issue was fixed thanks to this PR https://github.com/t3l3machus/hoaxshell/pull/2 - pending approval from @t3l3machus  to merge to main

**Comment by t3l3machus** [comment]
Hi, PR merged. It's weird that this issue came up, i thought i dealt with it at an earlier stage of development. Anyway, @brightio quick-fixed it. Thanks guys

**Comment by brightio** [comment]
Been there done that 🤣
