### ISSUE TITLE
How to use hoaxshell with ngrok? 

### ISSUE THREAD

**Issue by MhmadSal** [t3l3machus/hoaxshell#30]
I already have ngrok installed but when I use the command python3 hoaxshell.py - ng it says ngrok is not installed.

Do I need to modify the code in hoaxshell.py to get ngrok to work? If yes please tell me how to do it.

**Comment by t3l3machus** [comment]
@MhmadSal make sure ngrok binary is in your PATH.

**Comment by MhmadSal** [comment]
@t3l3machus I already downloaded ngrok in the hoaxshell folder but still the same issue, is there anything else I can do?

Or do you think I should move ngrok to another place rather than the hoaxshell folder?

**Comment by t3l3machus** [comment]
@MhmadSal you have to move it in one of the dirs that is included in your user's PATH environmental variable (i'm assuming you are using linux). Try for example moving the ngrok binary to `/usr/sbin/`.
*Also, do `chmod +x ngrok` (in case you haven't already).

**Comment by MhmadSal** [comment]
@t3l3machus I'm using kali Linux in userland android and yes ngrok was already in my $Home directory which is the main user directory and hoaxshell didn't work with ngrok so I moved ngrok into the hoaxshell folder and it still doesn't work.

**Comment by MhmadSal** [comment]
@t3l3machus it's working now but it shows the invalid address error in red when executing the payload in powershell and it doesn't return a session, what's the solution for this?

**Comment by t3l3machus** [comment]
I just tested it right now it worked fine. Are you sure ngrok is executable? Do `echo $PATH`, ngrok must be moved in one of these directories. 
![image](https://user-images.githubusercontent.com/75489922/196046255-f9f958a3-48ab-43cc-92be-c4e2710bfbaf.png)

**Comment by t3l3machus** [comment]
@MhmadSal post a screenshot of the error bro i am not a wizard

**Comment by MhmadSal** [comment]
@t3l3machus everything goes well on my Linux like in this picture 
![Screenshot_20221016_192655_tech ula](https://user-images.githubusercontent.com/115937682/196046965-b694a0d9-a0e4-40d8-b0f2-723273c19be8.jpg)


But when I execute it on windows powershell this happens :

![Uploading IMG_20221016_193020.jpg…]()

**Comment by MhmadSal** [comment]
That's the error again

![Uploading IMG_20221016_193020.jpg…]()

**Comment by t3l3machus** [comment]
The error img doesn't load. You are running hoaxshell on a particular OS that it has not been tested on. I believe some string operation is failing due to OS characteristics. Try to debug it,

**Comment by MhmadSal** [comment]
@t3l3machus that's the error 

![Uploading Screenshot_20221016_195523_com.google.android.apps.docs.jpg…]()
`

**Comment by MhmadSal** [comment]
That's the error 
![Screenshot_20221016_195523_com google android apps docs](https://user-images.githubusercontent.com/115937682/196048208-6a485f0f-12c5-453f-b9bd-ca3f0a4fec07.jpg)

**Comment by MhmadSal** [comment]
@t3l3machus can you please tell me how to deal with the error in the picture?
