### ISSUE TITLE
Detected by fully patched Win10 Machine with no additional ANtivirus

### ISSUE THREAD

**Issue by w0lfzk1n** [t3l3machus/hoaxshell#33]
Hello there, i have tested Hoaxshell 3 days ago on my machine and it worked with fully patched windows with Defender active.

Now, when i launch the payload on target, it shows

"This skript contains malicious content and is blocked by your antivirus software"

sadly i have no screens or else, because my pc is in german.

**Comment by t3l3machus** [comment]
As of 2022-10-18, hoaxshell is detected by AMSI ([malware-encyclopedia](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=VirTool%3aPowerShell%2fXoashell.A&threatid=2147833654)). I added the -o (--obfuscate) option that seems to make generated payloads undetectable (for now). I will try to enhance the auto-obfuscate function in the future.

**Comment by w0lfzk1n** [comment]
Yes, i saw that option afterwards. Thank you :)

**Comment by t3l3machus** [comment]
@w0lfzk1n did it work? 😅

**Comment by w0lfzk1n** [comment]
@t3l3machus yes, by using the -o for generating the payload, it works on the patched device.
