### ISSUE TITLE
Being detected by Windows Defender even with --obfuscate

### ISSUE THREAD

**Issue by TheUnknown-007** [t3l3machus/hoaxshell#36]
I've used -H and -o.
And yet its being detected by Windows Defender (AMSI).
Is there a way to manually obfuscate and get it to work?

**Comment by t3l3machus** [comment]
Hi, there are many simple tricks you can do manually to obfuscate the raw payload and make it work. I am working on a new tool, kind of the evolution of hoaxshell that will hopefully be released soon and it will include an improved auto obfuscate function.
