### ISSUE TITLE
Got Blocked by Microsoft-Defender

### ISSUE THREAD

**Issue by irahari** [t3l3machus/hoaxshell#42]
<img width="428" alt="hoax_shell_kali" src="https://user-images.githubusercontent.com/58359548/202480306-809ffee9-345c-4502-9b06-14345632a663.png">

<img width="431" alt="hoaxshell_powershell" src="https://user-images.githubusercontent.com/58359548/202480487-5a4f21ec-83eb-4c0c-9922-b65aa83af7a5.png">

**Comment by coderMohammed1** [comment]
just use AMSI bypass or better check https://www.revshells.com/ some of the payload do not even need this
