### ISSUE TITLE
Logo kindof sus

### ISSUE THREAD

**Issue by TheDracon** [t3l3machus/hoaxshell#53]
Ngl the "X" character in the logo is looking kindof sus ඞ

**Comment by sammypanda** [comment]
yea +1 the x looks far too much like a swastika. In modern context, it suggests neo-nazi affiliation

**Comment by t3l3machus** [comment]
Guys, this has been discussed before (check out closed issues, reddit). It's just auto generated ascii text art printed via a coloring function.  
![image](https://github.com/t3l3machus/hoaxshell/assets/75489922/f3548d04-0143-4500-8dcc-fd47a06e5b1c)
