### ISSUE TITLE
No shell ?

### ISSUE THREAD

**Issue by SmailDH** [t3l3machus/hoaxshell#59]
Hi Team,
Could anyone advise why i am receiving the connection back when try with netcat but nothing happening when i start the listener ?
![image](https://github.com/t3l3machus/hoaxshell/assets/90631526/1bbc14ae-81f6-42f8-9336-3be3fe1621ee)

**Comment by t3l3machus** [comment]
@SmailDH it looks like the cmd payload you used with cme is using https, but the hoaxshell server was not started with `-c` and `-p`, used to provide certificate and private key files to start the listener via https. Maybe if you change `protocol=https` to `protocol=http` in the payload, it will actually work. 

Another suggestion is to use [Villain](https://github.com/t3l3machus/Villain), which has the hoaxshell listener built-in and can also generate payloads (like the cmd-curl you are using) quickly, among other things. 

hope it helps!

**Comment by SmailDH** [comment]
Thank you @t3l3machus , Yes it did work with "http" but doesn't look it handle the display very well, i will try to use the Villain as suggested :)

![image](https://github.com/t3l3machus/hoaxshell/assets/90631526/4afbfe2b-7053-4567-914c-bbd7507d1b38)

**Comment by t3l3machus** [comment]
@SmailDH please let me know if you had the same issue with villain.

**Comment by SmailDH** [comment]
> @SmailDH please let me know if you had the same issue with villain.

I will do , thank you!
