### ISSUE TITLE
Question ??

### ISSUE THREAD

**Issue by badi2nou9** [t3l3machus/hoaxshell#7]
How to get file in system ??

**Comment by GNEUGNEUGNEU** [comment]
wdym ? if you type dir in remote shell it should output the file/directories

**Comment by t3l3machus** [comment]
What you actually mean is unclear @badi2nou9 
To read the contents of a file via powershell you can use the commands `type filename.txt` or `cat filename.txt`
For file transfers between attacker and victim machines there are many options. You can read about it [here](https://www.hackingarticles.in/file-transfer-cheatsheet-windows-and-linux/), You can find plenty of other sources online.
