### ISSUE TITLE
Don't use IE

### ISSUE THREAD

**Issue by moyvting** [t3l3machus/hoaxshell#8]
if you never used IE ,You can avoid this attack. 
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/39888034/187161237-231babc2-611b-4b06-8b89-ed7ec2c88c24.png">

**Comment by GNEUGNEUGNEU** [comment]
good to know

**Comment by corsch** [comment]
Especially as IE is no longer visible on modern Windows systems.

I had the same issue on a testing machine. "Workaround" is to finish the IE Wizard.

**Comment by effektsvk** [comment]
That is due to `Invoke-WebRequest`, I think it's possible to replace it with `Invoke-RestMethod`. That is what I used in my script for downloading Google Chrome (https://github.com/effektsvk/getchrome-function).

**Comment by t3l3machus** [comment]
Thank you for your input @moyvting @corsch @effektsvk 
This was really useful. I just added the `-i` option that generates the PS payload adjusted to use "Invoke-RestMethod' instead of 'Invoke-WebRequest', so now the user can choose.
